CREATE SEQUENCE seq_qna
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_qna_reply
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_studynote
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_withdraw
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_manager
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_faq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_group_report
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_notice
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_member_report
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_message
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_timer
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_chatting
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_user_info
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_studygroup
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_group_file
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_group_reply
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_group_msg
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_page_board
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_group_schedule
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_group_chatting
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_schedule
START WITH 1
INCREMENT BY 1;

