CREATE TABLE CATEGORY
(
	CATEGORY_NO          NUMBER NOT NULL ,
	CATEGORY_NAME        VARCHAR2(20) NULL 
);

ALTER TABLE CATEGORY
	ADD CONSTRAINT  XPK카테고리 PRIMARY KEY (CATEGORY_NO);

CREATE TABLE USER_INFO
(
	USER_NO              NUMBER NOT NULL ,
	USER_ID              VARCHAR2(20) NULL ,
	USER_PW              VARCHAR2(20) NULL ,
	USER_LASTNAME        VARCHAR2(20) NULL ,
	USER_FIRSTNAME       VARCHAR2(20) NULL ,
	USER_PHONENO         VARCHAR2(20) NULL ,
	USER_POST            VARCHAR2(10) NULL ,
	USER_BIRTH           DATE NULL ,
	USER_EMAIL           VARCHAR2(50) NULL ,
	CATEGORY_NO          NUMBER NOT NULL ,
	USER_ADDRESS1        VARCHAR2(100) NULL ,
	USER_ADDRESS2        VARCHAR2(200) NULL ,
	USER_REGISTER_DATE   DATE NULL 
);

ALTER TABLE USER_INFO
	ADD CONSTRAINT  XPK회원 PRIMARY KEY (USER_NO);

CREATE TABLE TIMER
(
	TIMER_NO             NUMBER NOT NULL ,
	TIME                 CHAR(100) NULL ,
	USER_NO              NUMBER NULL ,
	TIMER_DATE           DATE NULL 
);

ALTER TABLE TIMER
	ADD CONSTRAINT  XPK개인_타이머 PRIMARY KEY (TIMER_NO);

CREATE TABLE STUDYNOTE
(
	STUDYNOTE_NO         NUMBER NOT NULL ,
	STUDYNOTE_KEYWORD    VARCHAR2(100) NULL ,
	STUDYNOTE_CONTENT    VARCHAR2(1000) NULL ,
	STUDYNOTE_FILE       VARCHAR2(100) NULL ,
	STUDYNOTE_DATE       DATE NULL ,
	USER_NO              NUMBER NOT NULL 
);

ALTER TABLE STUDYNOTE
	ADD CONSTRAINT  XPK공부일기 PRIMARY KEY (STUDYNOTE_NO);

CREATE TABLE WITHDRAW
(
	WITHDRAW_REASON      VARCHAR2(10) NULL ,
	USER_NO              NUMBER NOT NULL ,
	ISWITHDRAW           CHAR(1) NULL 
);

ALTER TABLE WITHDRAW
	ADD CONSTRAINT  XPK탈퇴 PRIMARY KEY (USER_NO);

CREATE TABLE MEMBER_REPORT
(
	MEMBER_REPORT_NO     NUMBER NOT NULL ,
	MEMBER_REPORT_REASON VARCHAR2(500) NULL ,
	ISPROCESSING         CHAR(1) NULL ,
	USER_NO              NUMBER NULL ,
	REPORTER_ID          VARCHAR2(20) NULL 
);

ALTER TABLE MEMBER_REPORT
	ADD CONSTRAINT  XPK회원_신고 PRIMARY KEY (MEMBER_REPORT_NO);

CREATE TABLE CHATTING
(
	CHATTING_NO          NUMBER NOT NULL ,
	ISCHATREAD           CHAR(1) NULL ,
	USER_NO              NUMBER NOT NULL ,
	RECEIVER_ID          VARCHAR(20) NULL 
);

ALTER TABLE CHATTING
	ADD CONSTRAINT  XPK개인_채팅 PRIMARY KEY (CHATTING_NO);

CREATE TABLE STUDYGROUP
(
	STUDYGROUP_NO        NUMBER NOT NULL ,
	STUDYGROUP_NAME      VARCHAR2(100) NULL ,
	STUDYGROUP_INFO      VARCHAR2(1000) NULL ,
	STUDYGROUP_LOCATION  VARCHAR2(100) NULL ,
	REPORT_NUMBER        NUMBER NULL ,
	MAX_USER_NUMBER      NUMBER NULL ,
	CURRENT_USER_NUMBER  NUMBER NULL ,
	MADE_DATE            DATE NULL ,
	ISDELETE             CHAR(1) NULL ,
	ISFACE               CHAR(1) NULL ,
	CATEGORY_NO          NUMBER NOT NULL ,
	USER_NO              NUMBER NOT NULL 
);

ALTER TABLE STUDYGROUP
	ADD CONSTRAINT  XPK스터디_그룹 PRIMARY KEY (STUDYGROUP_NO);

CREATE TABLE GROUPUSER
(
	USER_NO              NUMBER NOT NULL ,
	STUDYGROUP_NO        NUMBER NOT NULL 
);

ALTER TABLE GROUPUSER
	ADD CONSTRAINT  XPK그룹원_목록 PRIMARY KEY (USER_NO,STUDYGROUP_NO);

CREATE TABLE APPLY_GROUP_MEMBER
(
	ISACCEPT             CHAR(1) NULL ,
	USER_NO              NUMBER NOT NULL ,
	STUDYGROUP_NO        NUMBER NOT NULL 
);

ALTER TABLE APPLY_GROUP_MEMBER
	ADD CONSTRAINT  XPK스터디그룹가입신청 PRIMARY KEY (USER_NO,STUDYGROUP_NO);

CREATE TABLE GROUP_REPORT
(
	GROUP_REPORT_NO      NUMBER NOT NULL ,
	GROUP_REPORT_REASON  VARCHAR2(100) NULL ,
	GROUP_ISPROCESSING   CHAR(1) NULL ,
	USER_NO              NUMBER NOT NULL ,
	STUDYGROUP_NO        NUMBER NOT NULL 
);

ALTER TABLE GROUP_REPORT
	ADD CONSTRAINT  XPK그룹_신고 PRIMARY KEY (GROUP_REPORT_NO);

CREATE TABLE GROUP_FILE
(
	GROUP_FILE_NO        NUMBER NOT NULL ,
	GROUP_FILE           VARCHAR2(100) NULL ,
	FILE_SIZE            VARCHAR2(10) NULL ,
	FILE_TITLE           VARCHAR2(100) NULL ,
	STUDYGROUP_NO        NUMBER NOT NULL 
);

ALTER TABLE GROUP_FILE
	ADD CONSTRAINT  XPK그룹파일보관함 PRIMARY KEY (GROUP_FILE_NO);

CREATE TABLE GROUP_CHATTING
(
	USER_NO              NUMBER NULL ,
	STUDYGROUP_NO        NUMBER NOT NULL ,
	GROUP_CHATTING_NO    NUMBER NOT NULL 
);

ALTER TABLE GROUP_CHATTING
	ADD CONSTRAINT  XPK회원_단체_채팅 PRIMARY KEY (GROUP_CHATTING_NO);

CREATE TABLE GROUP_MSG
(
	GROUP_MSG_LOG        VARCHAR2(1000) NULL ,
	GROUP_MSG_DATE       DATE NULL ,
	GROUP_MSG_NO         NUMBER NOT NULL 
);

ALTER TABLE GROUP_MSG
	ADD CONSTRAINT  XPK단체_채팅_메시지 PRIMARY KEY (GROUP_MSG_NO);

CREATE TABLE GROUP_PAGE_BOARD
(
	PAGE_BOARD_NO        NUMBER NOT NULL ,
	PAGE_BOARD_TITLE     VARCHAR2(100) NULL ,
	PAGE_BOARD_CONTENT   VARCHAR2(1000) NULL ,
	PAGE_BOARD_WRITER    VARCHAR2(100) NULL ,
	PAGE_BOARD_DATE      DATE NULL ,
	PAGE_BOARD_FILE      VARCHAR2(100) NULL ,
	STUDYGROUP_NO        NUMBER NOT NULL 
);

ALTER TABLE GROUP_PAGE_BOARD
	ADD CONSTRAINT  XPK그룹페이지게시물 PRIMARY KEY (PAGE_BOARD_NO);

CREATE TABLE GROUP_REPLY
(
	GROUP_REPLY_NO       NUMBER NOT NULL ,
	GROUP_REPLY_WRITER   VARCHAR2(100) NULL ,
	GROUP_REPLY_CONTENT  VARCHAR2(100) NULL ,
	PAGE_BOARD_NO        NUMBER NOT NULL 
);

ALTER TABLE GROUP_REPLY
	ADD CONSTRAINT  XPK그룹게시물댓글 PRIMARY KEY (GROUP_REPLY_NO);

CREATE TABLE GROUP_SCHEDULE
(
	GROUP_SCHEDULE_NO    NUMBER NOT NULL ,
	G_SCHEDULE_CONTENT   VARCHAR2(500) NULL ,
	G_START_DATE         DATE NULL ,
	G_START_TIME         DATE NULL ,
	G_END_DATE           DATE NULL ,
	G_END_TIME           DATE NULL ,
	G_SCHEDULE_MEMO      VARCHAR2(100) NULL ,
	STUDYGROUP_NO        NUMBER NOT NULL 
);

ALTER TABLE GROUP_SCHEDULE
	ADD CONSTRAINT  XPK스터디_일정 PRIMARY KEY (GROUP_SCHEDULE_NO);

CREATE TABLE SCHEDULE
(
	SCHEDULE_NO          NUMBER NOT NULL ,
	SCHEDULE_CONTENT     VARCHAR2(100) NULL ,
	SCHEDULE_START_DATE  DATE NULL ,
	SCHEDULE_START_TIME  DATE NULL ,
	SCHEDULE_END_DATE    DATE NULL ,
	SCHEDULE_END_TIME    DATE NULL ,
	SCHEDULE_MEMO        VARCHAR2(100) NULL ,
	USER_NO              NUMBER NOT NULL ,
	GROUP_SCHEDULE_NO    NUMBER NULL 
);

ALTER TABLE SCHEDULE
	ADD CONSTRAINT  XPK개인일정 PRIMARY KEY (SCHEDULE_NO);

CREATE TABLE MANAGER
(
	MANAGER_NO           NUMBER NOT NULL ,
	MANAGER_ID           VARCHAR2(20) NULL ,
	MANAGER_PW           VARCHAR2(20) NULL 
);

ALTER TABLE MANAGER
	ADD CONSTRAINT  XPK관리자 PRIMARY KEY (MANAGER_NO);

CREATE TABLE NOTICE
(
	NOTICE_NO            NUMBER NOT NULL ,
	NOTICE_TITLE         VARCHAR2(100) NULL ,
	NOTICE_CONTENT       VARCHAR2(1000) NULL ,
	NOTICE_DATE          DATE NULL ,
	MANAGER_NO           NUMBER NOT NULL 
);

ALTER TABLE NOTICE
	ADD CONSTRAINT  XPK공지사항 PRIMARY KEY (NOTICE_NO);

CREATE TABLE FAQ
(
	FAQ_NO               NUMBER NOT NULL ,
	FAQ_TITLE            VARCHAR2(500) NULL ,
	FAQ_CONTENT          VARCHAR2(1000) NULL ,
	MANAGER_NO           NUMBER NOT NULL 
);

ALTER TABLE FAQ
	ADD CONSTRAINT  XPK자주_묻는_질문 PRIMARY KEY (FAQ_NO);

CREATE TABLE MESSAGE
(
	CHATTING_LOG         VARCHAR2(1000) NULL ,
	CHATTING_NO          NUMBER NOT NULL ,
	CHATTING_DATE        DATE NULL 
);

ALTER TABLE MESSAGE
	ADD CONSTRAINT  XPK메시지 PRIMARY KEY (CHATTING_NO);

CREATE TABLE QNA
(
	QNA_NO               NUMBER NOT NULL ,
	QNA_TITLE            VARCHAR2(100) NULL ,
	QNA_CONTENT          VARCHAR2(1000) NULL ,
	QNA_DATE             DATE NULL ,
	ISREAD               CHAR(1) NULL ,
	USER_NO              NUMBER NOT NULL 
);

ALTER TABLE QNA
	ADD CONSTRAINT  XPK1대1_문의 PRIMARY KEY (QNA_NO);

CREATE TABLE QNA_REPLY
(
	QNA_REPLY_NO         NUMBER NOT NULL ,
	QNA_REPLY_CONTENT    VARCHAR2(1000) NULL ,
	QNA_REPLY_DATE       DATE NULL ,
	MANAGER_NO           NUMBER NOT NULL ,
	QNA_NO               NUMBER NULL 
);

ALTER TABLE QNA_REPLY
	ADD CONSTRAINT  XPK문의_댓글 PRIMARY KEY (QNA_REPLY_NO);

ALTER TABLE USER_INFO
	ADD (CONSTRAINT R_1 FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY (CATEGORY_NO));

ALTER TABLE TIMER
	ADD (CONSTRAINT R_2 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO) ON DELETE SET NULL);

ALTER TABLE STUDYNOTE
	ADD (CONSTRAINT R_3 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE WITHDRAW
	ADD (CONSTRAINT R_4 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE MEMBER_REPORT
	ADD (CONSTRAINT R_56 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO) ON DELETE SET NULL);

ALTER TABLE CHATTING
	ADD (CONSTRAINT R_19 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE STUDYGROUP
	ADD (CONSTRAINT R_5 FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY (CATEGORY_NO));

ALTER TABLE STUDYGROUP
	ADD (CONSTRAINT R_24 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE GROUPUSER
	ADD (CONSTRAINT R_123 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE GROUPUSER
	ADD (CONSTRAINT R_234 FOREIGN KEY (STUDYGROUP_NO) REFERENCES STUDYGROUP (STUDYGROUP_NO));

ALTER TABLE APPLY_GROUP_MEMBER
	ADD (CONSTRAINT R_40 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE APPLY_GROUP_MEMBER
	ADD (CONSTRAINT R_41 FOREIGN KEY (STUDYGROUP_NO) REFERENCES STUDYGROUP (STUDYGROUP_NO));

ALTER TABLE GROUP_REPORT
	ADD (CONSTRAINT R_51 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE GROUP_REPORT
	ADD (CONSTRAINT R_53 FOREIGN KEY (STUDYGROUP_NO) REFERENCES STUDYGROUP (STUDYGROUP_NO));

ALTER TABLE GROUP_FILE
	ADD (CONSTRAINT R_44 FOREIGN KEY (STUDYGROUP_NO) REFERENCES STUDYGROUP (STUDYGROUP_NO));

ALTER TABLE GROUP_CHATTING
	ADD (CONSTRAINT R_12 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO) ON DELETE SET NULL);

ALTER TABLE GROUP_CHATTING
	ADD (CONSTRAINT R_32 FOREIGN KEY (STUDYGROUP_NO) REFERENCES STUDYGROUP (STUDYGROUP_NO));

ALTER TABLE GROUP_MSG
	ADD (CONSTRAINT R_33 FOREIGN KEY (GROUP_MSG_NO) REFERENCES GROUP_CHATTING (GROUP_CHATTING_NO));

ALTER TABLE GROUP_PAGE_BOARD
	ADD (CONSTRAINT R_45 FOREIGN KEY (STUDYGROUP_NO) REFERENCES STUDYGROUP (STUDYGROUP_NO));

ALTER TABLE GROUP_REPLY
	ADD (CONSTRAINT R_343 FOREIGN KEY (PAGE_BOARD_NO) REFERENCES GROUP_PAGE_BOARD (PAGE_BOARD_NO));

ALTER TABLE GROUP_SCHEDULE
	ADD (CONSTRAINT R_11 FOREIGN KEY (STUDYGROUP_NO) REFERENCES STUDYGROUP (STUDYGROUP_NO));

ALTER TABLE SCHEDULE
	ADD (CONSTRAINT R_47 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE SCHEDULE
	ADD (CONSTRAINT R_48 FOREIGN KEY (GROUP_SCHEDULE_NO) REFERENCES GROUP_SCHEDULE (GROUP_SCHEDULE_NO) ON DELETE SET NULL);

ALTER TABLE NOTICE
	ADD (CONSTRAINT R_5987 FOREIGN KEY (MANAGER_NO) REFERENCES MANAGER (MANAGER_NO));

ALTER TABLE FAQ
	ADD (CONSTRAINT R_2342 FOREIGN KEY (MANAGER_NO) REFERENCES MANAGER (MANAGER_NO));

ALTER TABLE MESSAGE
	ADD (CONSTRAINT R_20 FOREIGN KEY (CHATTING_NO) REFERENCES CHATTING (CHATTING_NO));

ALTER TABLE QNA
	ADD (CONSTRAINT R_58 FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO));

ALTER TABLE QNA_REPLY
	ADD (CONSTRAINT R_57 FOREIGN KEY (MANAGER_NO) REFERENCES MANAGER (MANAGER_NO));

ALTER TABLE QNA_REPLY
	ADD (CONSTRAINT R_31 FOREIGN KEY (QNA_NO) REFERENCES QNA (QNA_NO) ON DELETE SET NULL);